### ISSUE TITLE
[Bug]: Error: incomplete frame

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ollm/OpenComic#258]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0.master.ea09830

### Operating System

WIN 10 22H2 19045.3324

### Steps to reproduce

Open this program.

### Expected Behavior

No errors

### Actual Behavior

![2024-08-07_13-16-33](https://github.com/user-attachments/assets/e4652c38-8e1c-4ae3-bed6-2ae53ba6d37a)

### Error message

```
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file._images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:398:44)
    at async file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:469:17)
    at async Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:18)
    at async processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:5)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:372:28
    at new Promise (<anonymous>)
    at _indexFiles (C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:342:9)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:391:20
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:372:28
    at new Promise (<anonymous>)
    at _indexFiles (C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:342:9)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:391:20
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:372:28
    at new Promise (<anonymous>)
    at _indexFiles (C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:342:9)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:391:20
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379 Uncaught (in promise) Error: Error: incomplete frame
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379:14
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379 Uncaught (in promise) Error: Error: incomplete frame
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379:14
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379 Uncaught (in promise) Error: Error: incomplete frame
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379:14
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:372:28
    at new Promise (<anonymous>)
    at _indexFiles (C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:342:9)
    at search (C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:82:27)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:376
C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379 Uncaught (in promise) Error: Error: incomplete frame
    at C:\Program Files\OpenComic\resources\app.asar\scripts\dom\search.js:379:14
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file._images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:398:44)
    at async file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:469:17)
    at async Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:18)
    at async processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:5)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
await in processTheQueue (async)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31
processTicksAndRejections @ node:internal/process/task_queues:77
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
processTicksAndRejections @ node:internal/process/task_queues:95
await in processTicksAndRejections (async)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31
processTicksAndRejections @ node:internal/process/task_queues:77
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
processTicksAndRejections @ node:internal/process/task_queues:95
await in processTicksAndRejections (async)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31
processTicksAndRejections @ node:internal/process/task_queues:77
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
processTicksAndRejections @ node:internal/process/task_queues:95
await in processTicksAndRejections (async)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31
processTicksAndRejections @ node:internal/process/task_queues:77
C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24 Error: incomplete frame
    at Object.readJson (C:\Program Files\OpenComic\resources\app.asar\scripts\cache.js:379:34)
    at file.readCompressed (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:210:20)
    at file.read (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:65:24)
    at file.images (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:459:36)
    at Boolean.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:1207:29)
    at processTheQueue (C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:15:28)
    at C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31:6
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
processTicksAndRejections @ node:internal/process/task_queues:95
await in processTicksAndRejections (async)
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:31
processTicksAndRejections @ node:internal/process/task_queues:77

```

**Comment by ollm** [comment]
Can you try clearing the app cache? (Settings > Clear cache), from the error message, it seems that some of the `json.zstd` files in the cache are corrupted.
