### ISSUE TITLE
[Bug]:  After search action,  error message : The "path" argument must be of type string. Received undefined  at Object.normalize 

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ollm/OpenComic#259]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0.master.ea09830

### Operating System

WIN 10 22H2 19045.3324

### Steps to reproduce

After search action,

### Expected Behavior

No errors

### Actual Behavior

Error message : The "path" argument must be of type string. Received undefined  at Object.normalize 

### Error message

```
processTheQueue @ C:\Program Files\OpenComic\resources\app.asar\scripts\queue.js:24
processTicksAndRejections @ node:internal/process/task_queues:95
node:internal/errors:541 Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.normalize (node:path:309:5)
    at Readable.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:1899:34)
    at Readable.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at Object.bodyData (C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\maybe.js:77:12)
    at C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\events.js:83:11
    at Socket.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (node:events:519:28)
normalize @ node:path:309
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:1899
emit @ node:events:519
addChunk @ node:internal/streams/readable:559
readableAddChunkPushObjectMode @ node:internal/streams/readable:536
Readable.push @ node:internal/streams/readable:391
bodyData @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\maybe.js:77
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\events.js:83
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64
emit @ node:events:519
addChunk @ node:internal/streams/readable:559
readableAddChunkPushByteMode @ node:internal/streams/readable:510
Readable.push @ node:internal/streams/readable:390
onStreamRead @ node:internal/stream_base_commons:191
C:\Program Files\OpenComic\resources\app.asar\node_modules\node-unrar-js\dist\js\unrar.js:9 Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.normalize (node:path:309:5)
    at Readable.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:1899:34)
    at Readable.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at Object.bodyData (C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\maybe.js:77:12)
    at C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\events.js:83:11
    at Socket.<anonymous> (C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (node:events:519:28)
normalize @ node:path:309
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\scripts\file-manager.js:1899
emit @ node:events:519
addChunk @ node:internal/streams/readable:559
readableAddChunkPushObjectMode @ node:internal/streams/readable:536
Readable.push @ node:internal/streams/readable:391
bodyData @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\maybe.js:77
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\events.js:83
(anonymous) @ C:\Program Files\OpenComic\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64
emit @ node:events:519
addChunk @ node:internal/streams/readable:559
readableAddChunkPushByteMode @ node:internal/streams/readable:510
Readable.push @ node:internal/streams/readable:390
onStreamRead @ node:internal/stream_base_commons:191
```

**Comment by ollm** [comment]
Try this fix 96babbd3fffef2bfe1b4141d349a7b98e19681b7

Build: https://mega.nz/file/2LgkVT7J#cK0Y58LTEF_0zwu5NsuygYYUzDYzyRTZSOjw8jtEXyo
