### ISSUE TITLE
[Bug]: "Error: Uncaught TypeError" when attempting to open bookmarks menu after navigating to a bookmark

### ISSUE THREAD

**Issue by fuhrizzy** [ollm/OpenComic#311]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.3.1

### Operating System

Windows 11 23H2 Build 22631.4602

### Installed via

.exe

### Steps to reproduce

1. While reading a file, open the bookmarks popout menu
2. Open a bookmark
3. Attempt to open the bookmarks popout menu again

### Expected Behavior

Bookmarks menu should open like normal

### Actual Behavior

Bookmarks menu does not open and shows an error instead

### Error message

Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeBackSlash (opencomic.js:923:16)
    at opencomic.js:1126:9
    at Function.<anonymous> (opencomic.js:1036:13)
    at Function.each (C:\Users\user\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383:19)
    at opencomic.js:1035:6
    at Function.each (C:\Users\user\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383:19)
    at Object.<anonymous> (opencomic.js:1025:4)
    at Object.wrapper (wrapHelper.js:10:19)
    at 17 (C:\Users\user\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:3038:100)
    at Object.prog [as inverse] (runtime.js:333:12)

### Additional Information

Using reverse reading mode and double page. In my testing changing this setting hasn't made a difference, but I thought it wouldn't hurt to mention it.

**Comment by ollm** [comment]
I have send a commit that might fix the problem 80c1b0eb7ea441e1f55a86713d04fe835089ef3d, although it could still happen.

If you want to try the fix you can install this build from the master branch.

Build: https://mega.nz/file/mT5z0JbY#o4AQyPkgxf_Vk_u8_n-JRFy_e9jnoZSKUANujCZCMEY
